const express = require('express');
const router = express.Router();
const controller = require('../../controller/account.controller');
const auth = require('../../middlewares/auth.mdw');
router.get('/register', controller.getRegister);
router.post('/register', controller.postRegister);
router.get('/is-available', controller.isAvailableAccount);
router.get('/login', controller.getLogin);
router.post('/login', controller.postLogin);
router.post('/logout', controller.postLogout);
router.get('/profile', auth, controller.getProfile);
module.exports = router;